/* eslint-disable react-hooks/exhaustive-deps */
import { RichTextEditor } from '@/components/shared'
import { FormItem, Input, InputGroup, Select, Switcher } from '@/components/ui'
import Addon from '@/components/ui/InputGroup/Addon'
import { useAppSelector } from '@/store'
import useGeneratePropertyDescription from '@/utils/hooks/useAutogenerateDescription'
import {
  filterBathrooms,
  filterBedrooms,
  filterFloors,
  filterTerraces,
  filterTypeOfHeating,
  filterTypeOfKitchens,
  filterTypeOfSecurity,
} from '@/utils/types/new-property/constants'
import { TSelect } from '@/utils/types/new-property/selects'
import { Field, FieldProps } from 'formik'
import { Dispatch, useCallback, useEffect, useState } from 'react'
import { HiInformationCircle } from 'react-icons/hi'
import { TbWorldSearch } from 'react-icons/tb'
import { FormModel } from './PropertyForm'
import {
  ContentPublishedProperty,
  ContentTypeOfHeating,
  ContentTypeOfKitchen,
} from './components/dialogs/ContentDialog'
import ShowDialog from './components/dialogs/ShowDialog'
import CommercialPremisesFields from './components/fields/CommercialPremisesFields'
import OfficeFields from './components/fields/OfficeFields'

const StepFormTwo = ({ values, touched, errors, setValues, setFieldValue }) => {
  const [userAuthority] = [useAppSelector((state) => state.auth.session.rol)]
  const [dialogTypeCaleIsOpen, setTypeCaleIsOpen] = useState<boolean>(false)
  const [dialogTypeOfKitchen, setDialogTypeOfKitchen] = useState<boolean>(false)
  const [dialogPublishedProperty, setDialogPublishedProperty] =
    useState<boolean>(false)
  const generateDescription = useGeneratePropertyDescription(
    values.step2,
    (updateFunction) => {
      setFieldValue('step2', updateFunction(values.step2))
    }
  )

  const handleGenerateDescription = () => {
    generateDescription()
  }

  const openDialog = useCallback(
    (setter: Dispatch<React.SetStateAction<boolean>>) => {
      setter(true)
    },
    []
  )

  const closeDialog = useCallback(
    (setter: Dispatch<React.SetStateAction<boolean>>) => {
      setter(false)
    },
    []
  )

  // Funtion to reset selects
  const resetValues = useCallback(
    (switcher: boolean | undefined, key: string) => {
      if (!switcher && values?.step2?.characteristics[key] !== '') {
        setValues((prevValues) => ({
          ...prevValues,
          step2: {
            ...prevValues.step2,
            characteristics: {
              ...prevValues.step2.characteristics,
              [key]: '',
            },
          },
        }))
      }
    },
    [setValues, values.step2.characteristics]
  )

  const resetArrayTypes = useCallback(() => {
    if (!values.step2.characteristics?.hasSecurity) {
      setValues((prevValues) => ({
        ...prevValues,
        step2: {
          ...prevValues.step2,
          characteristics: {
            ...prevValues.step2.characteristics,
            typeOfSecurity: [],
          },
        },
      }))
    }
  }, [values.step2.characteristics?.hasSecurity, setValues])

  useEffect(() => {
    // Este useEffect llama a resetArrayTypes cuando cambia el estado de hasSecurity
    resetArrayTypes()
  }, [values.step2.characteristics?.hasSecurity, resetArrayTypes])

  useEffect(() => {
    // Llama a resetValues basado en los estados de hasKitchen y hasHeating
    resetValues(values.step2.characteristics?.hasKitchen, 'typeOfKitchen')
    resetValues(values.step2.characteristics?.hasHeating, 'typeOfHeating')
  }, [
    // Dependencias ajustadas para reflejar la nueva ubicación en step2
    values.step2.characteristics?.hasKitchen,
    values.step2.characteristics?.hasHeating,
    values.step2.characteristics?.typeOfKitchen,
    values.step2.characteristics?.typeOfHeating,
    resetValues,
  ])

  // Si el tipo de inmueble seleccionado es diferente a Oficina se resetean los campos especiales de bodega
  useEffect(() => {
    if (values.step1.typeOfPropertyId !== 'Oficina') {
      setValues((prevValues) => ({
        ...prevValues,
        step2: {
          ...prevValues.step2,
          characteristics: {
            ...prevValues.step2.characteristics,
            numberOfPrivate: '',
            numberOfMeetingRooms: '',
            numberOfVacantFloors: '',
            hasKitchenet: false,
          },
        },
      }))
    }
  }, [
    values.step1.typeOfPropertyId,
    values.step2.characteristics?.numberOfPrivate,
    values.step2.characteristics?.numberOfVacantFloors,
    values.step2.characteristics?.numberOfMeetingRooms,
    values.step2.characteristics?.hasKitchenet,
  ])

  return (
    <>
      {userAuthority === 2 ? (
        <FormItem
          label="Enlace de la propiedad publicada en otros portales (Enlace público)."
          className="border-2 p-3 rounded-lg dark:border-gray-600"
          invalid={errors.step2?.externalLink && touched.step2?.externalLink}
          errorMessage={errors.step2?.externalLink}
        >
          <div className="absolute top-2 bottom-0 right-2">
            <button
              type="button"
              className="border-none bg-transparent"
              onClick={() => openDialog(setDialogPublishedProperty)}
            >
              <HiInformationCircle size={20} />
            </button>
          </div>
          <Field name="step2.externalLink">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Input
                  prefix={<TbWorldSearch className="text-xl" />}
                  field={field}
                  type="text"
                  size="md"
                  className="mb-2 border-lime-500/60 border-[3px] rounded-lg"
                  placeholder="Ej: https://www.portalinmobiliario.com/detalles-de-mi-publicacion"
                  value={values?.step2?.externalLink}
                  onChange={(e) => {
                    form.setFieldValue(field.name, e.target.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      ) : null}

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-0 md:grid-cols-2 md:gap-3 mt-4 place-content-center justify-items-center text-center">
        <FormItem label="¿En condominio?">
          <Field name="step2.characteristics.locatedInCondominium">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.locatedInCondominium}
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.locatedInCondominium
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Destacar Propiedad">
          <Field name="step2.highlighted">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.highlighted}
                  onChange={() => {
                    form.setFieldValue(field.name, !values?.step2?.highlighted)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      {userAuthority === 2 ? (
        <div className="w-full">
          <FormItem label="Observación y/o detalles">
            <Field name="step2.observations">
              {({ field, form }: FieldProps<FormModel>) => {
                return (
                  <Input
                    textArea
                    field={field}
                    size="md"
                    placeholder="Ingresa algo que necesita saber el comprador: Año de Propiedad, Ubicación cerca de..."
                    value={values?.step2?.observations}
                    onChange={(e) => {
                      form.setFieldValue(field.name, e.target.value)
                    }}
                  />
                )
              }}
            </Field>
          </FormItem>
        </div>
      ) : null}

      <div className="grid grid-cols-1 gap-0 md:grid-cols-2 md:gap-3">
        <FormItem
          label="Superficie de terreno"
          invalid={
            errors.step2?.characteristics?.surface &&
            touched.step2?.characteristics?.surface
          }
          errorMessage={errors.step2?.characteristics?.surface}
        >
          <Field name="step2.characteristics.surface">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <InputGroup>
                  <Input
                    type="number"
                    field={field}
                    size="md"
                    placeholder="Ej: 200 - 100.5"
                    value={values?.step2?.characteristics?.surface}
                    onChange={(e) => {
                      form.setFieldValue(field.name, e.target.value)
                    }}
                  />
                  <Addon size="md">m2</Addon>
                </InputGroup>
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Superficie construida">
          <Field name="step2.characteristics.constructedSurface">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <InputGroup>
                  <Input
                    type="number"
                    field={field}
                    size="md"
                    placeholder="Ej: 200"
                    value={values?.step2?.characteristics?.constructedSurface}
                    onChange={(e) => {
                      form.setFieldValue(field.name, e.target.value)
                    }}
                  />
                  <Addon size="md">m2</Addon>
                </InputGroup>
              )
            }}
          </Field>
          {errors.step2?.characteristics?.constructedSurface && (
            <span className="text-red-500">
              {errors.step2?.characteristics?.constructedSurface}
            </span>
          )}
        </FormItem>
      </div>

      {values?.step1?.typeOfPropertyId === 'Oficina' && (
        <OfficeFields values={values} />
      )}

      {values?.step1?.typeOfPropertyId === 'Local Comercial' && (
        <CommercialPremisesFields values={values} />
      )}

      <div className="grid grid-cols-1 gap-0 md:grid-cols-2 md:gap-3">
        <FormItem label="Número de Piso(s)">
          <Field name="step2.characteristics.numberOfFloors">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isClearable
                  field={field}
                  options={filterFloors}
                  placeholder="Seleccionar"
                  value={filterFloors?.filter(
                    (option: TSelect) =>
                      option.value ===
                      values?.step2?.characteristics?.numberOfFloors
                  )}
                  onChange={(option: TSelect) => {
                    form.setFieldValue(field.name, option?.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Terraza(s)">
          <Field name="step2.characteristics.terraces">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isClearable
                  field={field}
                  options={filterTerraces}
                  placeholder="Seleccionar"
                  value={filterTerraces?.filter(
                    (option: TSelect) =>
                      option.value === values?.step2?.characteristics?.terraces
                  )}
                  onChange={(option: TSelect) => {
                    form.setFieldValue(field.name, option?.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      <div className="grid grid-cols-1 gap-0 md:grid-cols-2 md:gap-3">
        <FormItem label="Baño(s)">
          <Field name="step2.characteristics.bathrooms">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isClearable
                  field={field}
                  options={filterBathrooms}
                  placeholder="Seleccionar"
                  value={filterBathrooms?.filter(
                    (option: TSelect) =>
                      option.value === values?.step2?.characteristics?.bathrooms
                  )}
                  onChange={(option: TSelect) => {
                    form.setFieldValue(field.name, option?.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Dormitorio(s)">
          <Field name="step2.characteristics.bedrooms">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isClearable
                  field={field}
                  options={filterBedrooms}
                  placeholder="Seleccionar"
                  value={filterBedrooms?.filter(
                    (option: TSelect) =>
                      option.value === values?.step2?.characteristics?.bedrooms
                  )}
                  onChange={(option: TSelect) => {
                    form.setFieldValue(field.name, option?.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      <div className="grid grid-cols-2 gap-0 md:gap-3">
        <FormItem
          label="Cocina(s)"
          className="flex justify-items-center items-start md:items-center"
        >
          <Field name="step2.characteristics.hasKitchen">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasKitchen}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasKitchen
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Tipo">
          <div className="absolute top-0 bottom-0 right-0">
            <button
              type="button"
              className="border-none bg-transparent"
              onClick={() => openDialog(setDialogTypeOfKitchen)}
            >
              <HiInformationCircle size={20} />
            </button>
          </div>
          <Field name="step2.characteristics.typeOfKitchen">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isClearable
                  isDisabled={!values?.step2?.characteristics?.hasKitchen}
                  field={field}
                  options={filterTypeOfKitchens}
                  placeholder="Seleccionar"
                  value={filterTypeOfKitchens?.filter(
                    (option: TSelect) =>
                      option.value ===
                      values?.step2?.characteristics?.typeOfKitchen
                  )}
                  onChange={(option: TSelect) => {
                    form.setFieldValue(field.name, option?.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      <div className="grid grid-cols-2 gap-0 md:gap-3">
        <FormItem
          label="Calefacción"
          className="flex justify-items-center items-start md:items-center"
        >
          <Field name="step2.characteristics.hasHeating">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasHeating}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasHeating
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Tipo" className="relative">
          <div className="absolute top-0 bottom-0 right-0">
            <button
              type="button"
              className="border-none bg-transparent"
              onClick={() => openDialog(setTypeCaleIsOpen)}
            >
              <HiInformationCircle size={20} />
            </button>
          </div>
          <Field name="step2.characteristics.typeOfHeating">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isClearable
                  isDisabled={!values?.step2?.characteristics?.hasHeating}
                  field={field}
                  options={filterTypeOfHeating}
                  placeholder="Seleccionar"
                  value={filterTypeOfHeating?.filter(
                    (option: TSelect) =>
                      option.value ===
                      values?.step2?.characteristics?.typeOfHeating
                  )}
                  onChange={(option: TSelect) => {
                    form.setFieldValue(field.name, option?.value)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      <div className="grid grid-cols-2 gap-0 md:gap-3">
        <FormItem
          label="Seguridad"
          className="flex justify-items-center items-start md:items-center"
        >
          <Field name="step2.characteristics.hasSecurity">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values.step2?.characteristics?.hasSecurity}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values.step2?.characteristics?.hasSecurity
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem
          label="Tipo"
          invalid={
            errors.step2?.characteristics?.typeOfSecurity &&
            touched.step2?.characteristics?.typeOfSecurity
          }
          errorMessage={errors.step2?.characteristics?.typeOfSecurity}
          className="relative"
        >
          <Field name="step2.characteristics.typeOfSecurity">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Select
                  isMulti
                  isClearable
                  isDisabled={!values?.step2?.characteristics?.hasSecurity}
                  placeholder="Seleccionar"
                  value={values?.step2?.characteristics?.typeOfSecurity}
                  options={filterTypeOfSecurity}
                  onChange={(option) => {
                    form.setFieldValue(field.name, option)
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-3 gap-0 md:gap-3 place-content-start md:place-content-center justify-items-start md:justify-items-center text-start md:text-center">
        <FormItem label="Amoblada">
          <Field name="step2.characteristics.isFurnished">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.isFurnished}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.isFurnished
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="A. acondicionado">
          <Field name="step2.characteristics.hasAirConditioning">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasAirConditioning}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasAirConditioning
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Garage">
          <Field name="step2.characteristics.hasGarage">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasGarage}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasGarage
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Estacionamiento(s)">
          <Field name="step2.characteristics.hasParking">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasParking}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasParking
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Ascensor">
          <Field name="step2.characteristics.hasElevator">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasElevator}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasElevator
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Gimnasio">
          <Field name="step2.characteristics.hasGym">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasGym}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasGym
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Piscina">
          <Field name="step2.characteristics.hasSwimmingPool">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2?.characteristics?.hasSwimmingPool}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasSwimmingPool
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>

        <FormItem label="Quincho">
          <Field name="step2.characteristics.hasBarbecueArea">
            {({ field, form }: FieldProps<FormModel>) => {
              return (
                <Switcher
                  checked={values?.step2.characteristics?.hasBarbecueArea}
                  className="my-3"
                  onChange={() => {
                    form.setFieldValue(
                      field.name,
                      !values?.step2?.characteristics?.hasBarbecueArea
                    )
                  }}
                />
              )
            }}
          </Field>
        </FormItem>
      </div>

      <FormItem
        asterisk
        label="Titulo de la Propiedad"
        invalid={
          errors?.step2?.characteristics?.propertyTitle &&
          touched?.step2?.characteristics?.propertyTitle
        }
        errorMessage={errors?.step2?.characteristics?.propertyTitle}
      >
        <Field name="step2.characteristics.propertyTitle">
          {({ field, form }: FieldProps<FormModel>) => {
            return (
              <Input
                field={field}
                type="text"
                size="md"
                className="mb-2"
                placeholder="Ingresar un titulo"
                value={values?.step2?.characteristics?.propertyTitle}
                onChange={(e) => {
                  form.setFieldValue(field.name, e.target.value)
                }}
              />
            )
          }}
        </Field>
      </FormItem>

      <FormItem
        label="Descripción de la Propiedad"
        className="mb-6"
        labelClass="!justify-start"
        invalid={
          errors?.step2?.characteristics?.propertyDescription &&
          touched?.step2?.characteristics?.propertyDescription
        }
        errorMessage={errors?.step2?.characteristics?.propertyDescription}
      >
        <div className="w-auto text-end mb-1.5 xs:mb-0 xs:absolute xs:top-0 xs:right-0 z-0">
          <button
            type="button"
            className="border-none text-gray-500 hover:text-gray-700"
            onClick={() => handleGenerateDescription()}
          >
            Generar descripción
          </button>
        </div>
        {
          // RichTextEditor component
          values.step2.characteristics.propertyDescription && (
            <Field name="step2.characteristics.propertyDescription">
              {({ field, form }: FieldProps) => (
                <RichTextEditor
                  value={field.value}
                  placeholder="Ingresar una descripción de la propiedad..."
                  onChange={(val) => {
                    form.setFieldValue(field.name, val)
                  }}
                />
              )}
            </Field>
          )
        }
      </FormItem>

      {/* Kitchen type dialog */}
      <ShowDialog
        closable
        title="Tipos de cocina"
        isOpen={dialogTypeOfKitchen}
        Content={<ContentTypeOfKitchen />}
        onClose={() => closeDialog(setDialogTypeOfKitchen)}
        onRequestClose={() => closeDialog(setDialogTypeOfKitchen)}
      />

      {/* Heating type dialog */}
      <ShowDialog
        closable
        title="Tipos de calefacción"
        isOpen={dialogTypeCaleIsOpen}
        Content={<ContentTypeOfHeating />}
        onClose={() => closeDialog(setTypeCaleIsOpen)}
        onRequestClose={() => closeDialog(setTypeCaleIsOpen)}
      />

      {/* External published property */}
      <ShowDialog
        closable
        title="Información sobre este campo"
        isOpen={dialogPublishedProperty}
        Content={<ContentPublishedProperty />}
        onClose={() => closeDialog(setDialogPublishedProperty)}
        onRequestClose={() => closeDialog(setDialogPublishedProperty)}
      />
    </>
  )
}

export default StepFormTwo
